dbmedialab/shiny

src/atoms/Kicker.js
stories/EditorialMarking.js
stories/Typography.js
stories/editorialMarking/kicker.js
stories/index.js

- Add new folder in stories for editorial marking stuff.
- Add kicker/deck atom and story
- Add style for kicker

Add kicker atom and story

---

.travis.yml

Snapshots from master builds will be the base for pull request snapshot
comparisons.

Send master builds to Percy as well

---

.storybook/config.js
src/atoms/ThemeSelector.js
src/index.js
src/molecules/ThemeSwitcher.js
src/storybook-decorators/ThemeSwitcher.js
stories/EditorialMarking.js
stories/FloatImage/index.js
stories/HorizontalLinkBar.js
stories/Loaders.js
stories/TrysilPlug/index.js
stories/Typography.js
stories/editorialMarking/kicker.js
stories/grid/index.js
stories/introduction/index.js
stories/storybook-components/index.js

Use a single addDecorator() call instead of adding it on every story

Use a single addDecorator() call instead of adding it on every story

---

src/atoms/HorizontalFlexingList.js
src/atoms/LinkBarItem.js

Allow dropdown menus to be clickable over elements with position relative

---

src/atoms/MainRecipe/Description.js
src/organisms/MainRecipe.js

Reduces number of DOM elements in #221

fix: Simplify Description

---

src/atoms/Heading.js
src/molecules/TrysilPlug.js
stories/TrysilPlug/all-caps.js
stories/TrysilPlug/index.js

It's actually sent right through to Heading, so even though ALLCAPS is usually a bad decision, at least now it's a reusable bad decision.

Add an ALLCAPS prop to TrysilPlug

---

stories/link-bars/DropdownStory.js

docs(LinkBarDropDown): Fix alignment in code example

---

src/atoms/BlockLinkWithBackground.js
src/atoms/DymoHeading.js
src/atoms/Kicker.js
src/atoms/Label.js
src/atoms/LunchKicker.js
src/atoms/NativeAdKicker.js
src/molecules/LunchButton.js
src/molecules/TrysilPlug.js
src/utils/get-color.js
src/utils/index.js
src/utils/unshade-color-string.js
stories/TrysilPlug/all-caps.js
stories/TrysilPlug/basic-issue.js
stories/TrysilPlug/custom-heading.js
stories/TrysilPlug/kicker.js
stories/TrysilPlug/row-with-three-plugs.js
stories/editorialMarking/kicker.js

feature: Add more props to Label

---

src/atoms/AdWrapper.js
src/molecules/WallpaperAd.js
src/themes/default-theme/colors.js
src/themes/default-theme/variables.js
src/themes/sol/colors.js
src/themes/sol/variables.js

fix: Make ad marking WCAG compliant

---

src/atoms/SvgIcon/OppskriftLogo.js
src/index.js
src/molecules/Footers/OppskriftFooter.js
stories/MatComponents/MatColophon.js
stories/MatComponents/footer.js
stories/link-bars/MatStory.js

Renamed footer to oppskrift

---

src/atoms/Heading.js
src/atoms/MainRecipe/ColorTextBox.js
src/atoms/UnderlinedHeading.js

ingredients page

---

src/atoms/AdWrapper.js
src/molecules/FullscreenAd.js
src/molecules/LazyProgressiveImage.js
src/molecules/WallpaperAd.js

Fix lazy images not blurring and div ad settings

---

src/atoms/MainRecipe/MoreLine.js

vis flere/ mobile view

---

src/molecules/MainRecipe/RecipeMetaData.js

order of elements from duplicates to css order

---

src/atoms/LinkBarLinkBase.js
src/atoms/MainRecipe/ColorTextBox.js
src/molecules/Footers/OppskriftFooter.js

Fixed issues that appears on oppskrift article page

---

src/atoms/AdWrapper.js

Fixes dbmedialab/wolverine-frontend#279

Fix proptypes warning for FullscreenAd

---

src/molecules/HorizontalHeroUnit.js

Added frameBorder prop to YT video inside of HorizontalHeroUnit.

---

package.json
yarn.lock

Greenkeeper/styled components 3.2.5

---

src/atoms/LinkBarDropdown.js
stories/link-bars/DropdownStory.js
stories/link-bars/LinkStory.js

Alternative approach in #373.
Fixes dbmedialab/wolverine-frontend#133.

Hide dropdowns on blur

---

src/atoms/Button.js
src/atoms/Error.js
src/index.js
stories/Typography.js
stories/typography/error.js

Add Error component

---

src/themes/dinside/index.js
src/themes/kk/index.js

See #295 - some improvements still to be made after this one.

feature: Add KK font definitions

---

src/index.js
stories/typography/numberedList.js

fix error with Code exporting

---

src/atoms/Heading.js

Remove faulty media query; fixes #403

---

package.json
yarn.lock

Greenkeeper/@percy io/percy storybook 1.3.5

---

package.json
yarn.lock

Greenkeeper/react modal 3.4.4

---

src/molecules/Footers/OppskriftFooter.js
src/themes/mat/variables.js

refactor oppskrift footer

---

yarn.lock

fix: Update lockfile

---

src/atoms/BorderedButton.js

change :focus to :active

---

.travis.yml
src/atoms/FrontHeading.js
src/atoms/SvgIcon/SvgIconWrapper.js
src/atoms/SvgIcon/index.js
src/themes/mat/variables.js

front heading adjustment

---

src/themes/mat/colors.js

New color for Oppskrift.no theme.

---

src/atoms/BlockLink.js
src/atoms/Kicker.js
src/molecules/TrysilPlug.js
stories/Typography.js
stories/typography/blocklink.js

refactor BlockLink

---

src/atoms/MainRecipe/ColorTextBox.js
src/molecules/NumberedList.js
src/themes/mat/variables.js

Refactor styles to match design 

---

src/atoms/RoundedButtons.js
src/index.js
src/molecules/ScrollArrowsLinkBar.js
stories/typography/buttons.js

Added RoundedButtons from Aurora

---

package.json
yarn.lock

Greenkeeper/eslint plugin react 7.8.2

---

package.json
yarn.lock

Greenkeeper/react intersection observer 4.0.2

---

.github/PULL_REQUEST_TEMPLATE.md

Add N/A options in PR template

---

src/themes/sol/index.js

Hack links on sol to their preexisting behavior with global styles. Should be redone at some point - see dbmedialab/wolverine-frontend#460

a underline rules for sol.no

---

src/atoms/ThemeSelector.js

Fix (global styles): Reduce number of injectGlobal calls

---

src/atoms/BorderedButton.js
src/atoms/Button.js
src/utils/luminance.js

refactor(Buttons): Extract fancy-pants luminance functions

---

src/index.js

fix 326; added export to UnderlinedXSmallHeading

---

src/themes/seher/variables.js

fix: Specify ui font sizes for Seher theme

---

.babelrc
package.json
yarn.lock

Closes #476; closes #481; closes #482; closes #483; closes #484; closes #485.

build: Upgrade babel packages to 7.0.0 beta 49

---

src/atoms/LinkBarDropdown.js

fix: Make dropdowns focusable (fixes #501)

---

.editorconfig
package.json

makes this repo unlisensed so we can publish it on npm.
https://docs.npmjs.com/files/package.json#license

Remove license

---

README.md
package.json

Release 0.4.0

---

README.md
package.json
stories/introduction/Welcome.js

docs: Improve documentation

---

package.json

build: Automatically deploy to github.io after publish

---

package.json
yarn.lock

Greenkeeper/eslint plugin react 7.9.1

---

src/atoms/DinsideLogo.js

Fix missing width and height on DinsideLogo

---

src/themes/dinside/colors.js
src/themes/dinside/index.js

Add missing Dinside styles

---

package.json
yarn.lock

Greenkeeper/lazysizes 4.0.4

---

package.json

fix(package): update react-intersection-observer to version 5.0.5

---

src/atoms/BorderedButton.js
src/utils/index.js

fix sticky hover behaviour on mobile devices; refactor

---

src/atoms/MainRecipe/IngredientsSection.js

fix calculate button position

---

package.json
src/atoms/Grid.js
yarn.lock

Greenkeeper/react styled flexboxgrid 2.4.0

---

package.json
yarn.lock

Greenkeeper/@babel/core 7.0.0 beta.51

---

package.json
yarn.lock

Greenkeeper/@babel/plugin transform object assign 7.0.0 beta.51

---

package.json
yarn.lock

Greenkeeper/@babel/preset react 7.0.0 beta.51

---

package.json

chore(package): update @babel/preset-env to version 7.0.0-beta.51

---

package.json

chore(package): update @babel/preset-stage-0 to version 7.0.0-beta.51

---

src/molecules/MainRecipe/RecipeMetaData.js

fix: preventing mediumPortrait of null error

---

package.json

Tag v0.5.4

---

package.json
yarn.lock

Greenkeeper/styled components 3.3.3

---

src/atoms/Heading.js
src/molecules/ThemeSwitcher.js
src/themes/default-theme/colors.js
src/themes/default-theme/variables.js
src/themes/index.js
src/themes/light-theme/index.js

Add Light theme

---

package.json
yarn.lock

Greenkeeper/babel eslint 8.2.5

---

src/atoms/LinkBarDropdown.js

fix: header hiding for client routing

---

src/atoms/FontIcon.js

add instagram icon

---

src/molecules/SearchField.js

refactor: SearchField molecule

---

src/themes/start/colors.js

fix(start): Flatten theme colors; switch primary/secondary

---

src/themes/start/colors.js
src/themes/start/index.js

fix(start): change backround color to what seems like the intention

---

src/atoms/Button.js

Added margin to buttons that was previously removed, to fix styling on oppskrift.no. Also changed padding to use verticalBase variable instead of being hardcoded.

fix: Add margin again and use verticalBase for padding for buttons

---

README.md
src/utils/css-reset.js

Trying webkit font size 100%

---

src/themes/start/variables.js

Fixing font-size for header-elements

---

src/atoms/LinkBarDropdown.js

refactor(LinkBarDropdown): Make code simpler

---

stories/link-bars/SeHerStory.js

fix: Fine tune seher-like linkbar story

---

package.json
yarn.lock

Greenkeeper/styled components 3.4.1

---

src/themes/start/colors.js

Fixing colors on start.no

---

src/atoms/DymoHeading.js
src/prop-types/index.js
stories/TrysilPlug/index.js
stories/TrysilPlug/text-color-hover.js

 refactor(DymoHeading): Use custom proptypes for colors and shades

---

package.json
yarn.lock

Greenkeeper/eslint plugin react 7.11.0

---

package.json
yarn.lock

Greenkeeper/eslint 5.0.1

---

package.json
yarn.lock

Greenkeeper/eslint plugin jsx a11y 6.1.1

---

package.json

build(package): Add "sideEffects: false"

---

.babelrc

fix: Skip default conversion

---

package.json
src/themes/seher/flexboxgrid.js
src/themes/seher/index.js

fix(seher): increase container sizes

---

src/molecules/Footers/OppskriftFooter.js

set editor value for OppskriftFooter

---

babel-transform-shiny.js
src/atoms/BodyText.js
src/atoms/RoundedButtons.js
src/index.js
src/storybook-decorators/ThemeSwitcher.js
src/themes/dagbladet/index.js
src/themes/default-theme/index.js
src/themes/default-theme/variables.js
src/themes/dinside/index.js
src/themes/kk/index.js
src/themes/light-theme/index.js
src/themes/seher/index.js
src/themes/seher/variables.js
src/themes/sol/index.js
src/themes/sol/variables.js
src/themes/start/index.js
src/themes/theme-prop-types.js

refactor: Move body styles from theme.global to Body component

---

package.json
yarn.lock

Greenkeeper/lazysizes 4.1.2

---

src/molecules/Footers/DinsideFooter.js

fix(DinsideFooter): refactor .extend to styled()

---

package.json
yarn.lock

Greenkeeper/monorepo.react 16.5.1

---

src/themes/seher/flexboxgrid.js
src/themes/seher/index.js
src/themes/seher/variables.js
stories/link-bars-complete-examples/SeHerStory.js

fix(SeHer): Configure seher theme, props @aprestmo

---

src/atoms/DymoHeading.js
stories/typography/dymo-heading.js
stories/typography/heading.js

fix(DymoHeading): Adjust spacing on transparent DymoHeadings

---

src/atoms/LinkBarElementBase.js
src/atoms/LinkBarSearchField.jsx
stories/link-bars-complete-examples/SeHerMenuRemake.js
stories/link-bars/HorizontalLinkBarStory.js

Another SeHer menu iteration

---

package.json
yarn.lock

fix(package): downgrade all emotion packages to 9.2.6

---

src/atoms/LinkBarElementBase.js
src/atoms/ShinyThemeProvider.js

fix(LinkBarElementBase): Fix proptype syntax for theme

---

src/atoms/LinkBarItem.js
src/atoms/VerticalFlexingList.js
src/molecules/HorizontalLinkBar.js
src/molecules/ScrollArrowsLinkBar.js
src/molecules/VerticalLinkBar.js
stories/link-bars-complete-examples/SeHerMenuRemake.js

fix: Style seher dropdown menu example for extra small screens

---

package.json
yarn.lock

Greenkeeper/babel eslint 10.0.1

---

package.json
yarn.lock

chore(package): update babel-plugin-react-docgen to version 2.0.0

---

package.json
yarn.lock

Greenkeeper/polished 2.1.1

---

src/molecules/TrysilPlug.js
stories/TrysilPlug/basic-issue.js

docs(TrysilPlug): Add jsdoc comments and use the withInfo addon

---

src/atoms/Article.js
src/molecules/TrysilPlug.js
stories/TrysilPlug/index.js
stories/TrysilPlug/with-col.js

feat: Let articles be a col

---

src/atoms/LinkBarSearchField.jsx

fix(LinkBarSearchField): Remove user agent styling on input field

---

src/atoms/LinkBarSearchField.jsx

Specify width, making sure that the width is narrow enough to be
displayed alongside the other elements currently in SeHer's menu.

fix(LinkBarSearchField): Specify width

---

src/atoms/LinkBarElementBase.js

fix(LinkBarElementBase): Revert specificity hack to fix regressions from 0.15.4

---

src/molecules/HorizontalLinkBar.js
stories/link-bars/HorizontalLinkBarStory.js
stories/link-bars/OverflowStory.js
stories/link-bars/index.js

docs(HorizontalLinkBars): Use withInfo and split into two stories

---

stories/link-bars-complete-examples/SeHerMenuRemake.js

docs(SeherMenuRemake): give logo some air

---

src/atoms/LinkBarElementBase.js

fix(LinkBarElementBase): Counteract :visited leakage from sh-styleguide

---

package.json
yarn.lock

Greenkeeper/react emotion 9.2.12

---

package.json
yarn.lock

Greenkeeper/polished 2.3.0

---

src/atoms/AllerLogo.js
src/molecules/ThemeSwitcher.js
src/themes/aller/index.js
src/themes/aller/variables.js
src/themes/index.js
stories/logos/AllerStory.js
stories/logos/index.js

feat: Add Aller theme and logo

---

src/themes/aller/flexboxgrid.js
src/themes/aller/index.js

refactor: Use smaller grid on aller theme

---

package.json
yarn.lock

Greenkeeper/monorepo.storybook 4.0.2

---

.travis.yml

ci(travis): add testing environment with node 10

---

src/themes/pregenerate.js

Generate themes to reduce bundlesize
We create a fake empty KK theme modules, since this is a very large due to fonts,

Prebuild themes except kk

---

package.json
yarn.lock

Greenkeeper/react intersection observer 6.3.1

---

package.json
yarn.lock

Greenkeeper/emotion theming 10.0.2

---

package-lock.json
package.json

Debug v4 do not transpile ES6 syntax, this means we need to use v3 of the package!

Downgrade debug package

---

stories/Images/figure-with-image-and-caption.js
stories/Images/image.js

docs(Image): change placeholder image provider

---

src/atoms/DymoHeading.js
src/atoms/Heading.js
src/atoms/Kicker.js
src/atoms/OverlayingPlugLabel.js
src/molecules/Labels.js
src/molecules/LazyProgressiveImage.js
src/molecules/OverlayingPlugLabels.js
src/molecules/TrysilPlug.js
stories/TrysilPlug/custom-labels.js

feature(TrysilPlug): Add the ability to change the order of elements

---

package.json
yarn.lock

chore(package): Upgrade storybook monorepo to 4.1.1

---

src/molecules/WallpaperAd.js

Remove zindex from wallpaper ad

---

package.json
yarn.lock

chore(package): re-upgrade striptags to 3.1.1

---

stories/storybook-components/index.js

fix(DemoContainer): Use variables in the DemoContainer component

---

package.json
yarn.lock

chore(package): Update storybook monorepo to version 4.1.6

---

src/atoms/CarouselSlot.js

refactor(CarouselSlot): Prefer const

---

src/atoms/ButtonWithModal.js
src/atoms/Error.js
src/atoms/LinkBarDropdown.js
src/atoms/RoundedButtons.js
src/molecules/Carousel.js
src/molecules/HorizontalHeroUnit.js
src/molecules/TrysilPlug.js

When accepting component props, accept both functional and stateful components.

refactor(prop-types): Accept both functional and stateful components

---

src/atoms/CarouselSlot.js

remove unnecessary margin from carousel slot component

---

package.json
yarn.lock

chore(package): Upgrade babel7 dependencies to version 7.3.1

---

package.json
yarn.lock

chore(package): upgrade storybook to 4.1.11

---

src/atoms/CarouselButton.js
src/molecules/Carousel.js
stories/web-app-components/Carousel/index.js
stories/web-app-components/Carousel/verticalWithoutButtons.js

add opportunity to use carousel without nav buttons

---

src/themes/elbil24/index.js
stories/link-bars-complete-examples/Elbil24Story.js

Elbil24 header

---

.babelrc
package.json
yarn.lock

build(babel): transform runtime (async generator)

---

src/themes/seher/index.js
src/themes/seher/variables.js

fix(seher): Change font from Source Sans Pro to Lato

---

src/atoms/Dot.js
src/atoms/MenuLayer.js
src/atoms/Truncate.js
src/index.js
src/themes/dagbladet/colors.js
src/themes/dagbladet/index.js
stories/link-bar-elements/MenuLayerStory.js
stories/link-bar-elements/index.js
stories/typography/dot.js
stories/typography/index.js
stories/typography/truncate.js

- feature(components): Add components Dot, MenuLayer(with simple animation), Truncate
These components will be used in the new dagbladet header
- fix(db theme): Increase verticalBase
(Jira: Dp 631)

feature: introduce components for new header dropdowns (Jira: DP-631)

---

src/themes/seher/index.js

fix(seher theme): Add missing font Lato 400

---

src/themes/default-theme/variables.js

fix(themes): add variable 'spacing'

---

src/atoms/VerticalFlexingList.js

fix(VerticalLinkBar): Make it easier to display nested link bars

---

src/themes/dagbladet/index.js

fix(db theme): configure the grid

---

src/themes/dagbladet/colors.js

fix(dagbladet theme): changed primary dark

---

src/molecules/LazyProgressiveImage.js

feat(LazyProgressiveImage): Support native lazyload

---

src/atoms/UnderlinedHeading.js

add props to UnderlinedHEading component:
lineWidth
lineHeight
lineColor
ALLCAPS

add props to UnderlinedHEading component

---

src/atoms/UnderlinedHeading.js

add mobileLine show/hide functionality

Refactoring(UnderlinedHeading)/add mobileLine show/hide functionality

---

src/atoms/LinkBarElementBase.js

The LinkBarElementBase was a unyielding beast. This
refactor splits it up into smaller pieces that can
more easily be turned into shared utils later on.

refactor(LinkBarElementBase): Divvy up into logical pieces

---

src/atoms/Truncate.js
stories/typography/truncate.js

feature(Truncate): Add properties: maxWidth, custom - array of key:value [{screenWidth, maxWidth}], what will be insert as a media query

feature(Truncate): Add properties maxWidth and custom

---

package.json

Release 0.30.0

---

src/organisms/UserDropdown.js
stories/link-bars-complete-examples/UserDropDown.js
stories/link-bars-complete-examples/index.js

…uiRegularSize, also can be uiSmallSize or uiTinySize

Feature/user dropdown/configurable font size

---

package.json

release 0.31.0

---

src/molecules/WallpaperAd.js

refactor(WallpaperAd): Remove unused media query method

---

src/atoms/Arrow.js

add shadow and change def color to white

---

src/atoms/Elbil24Logo.js
stories/logos/Elbil24LogoStory.js

Need elbil24 logo where colors are switched

---

src/atoms/IconWithText.js

fix(IconWithText): Center the component

---

src/atoms/LogiclessModal.js

fix(LogiclessModal): Make content smaller on mobile

---

src/organisms/UserDropdown.js

UserDropdown - relative urls instead of absolute

---

src/molecules/ThemeSwitcher.js
src/themes/elbil24-dark/index.js
src/themes/index.js
src/themes/pregenerate.js

Reinserting elbil24Dark theme

---

.travis.yml

ci(travis): remove greenkeeper-lockfile

---

.travis.yml

BREAKING: Drop support for node 9

---

src/atoms/SvgIcon/default/NoSound.js
src/atoms/SvgIcon/default/index.js
stories/typography/svgIcon.js

Feature(Icons): "No sound" svg icon

---

src/atoms/Label.js
src/atoms/LinkBarElementBase.js
src/themes/aller/variables.js
src/themes/dagbladet/index.js
src/themes/default-theme/variables.js
src/themes/dinside/index.js
src/themes/elbil24/index.js
src/themes/kk/index.js
src/themes/light-theme/index.js
src/themes/mat/variables.js
src/themes/seher/variables.js
src/themes/sol/variables.js
src/themes/start/variables.js
src/themes/theme-prop-types.js
src/themes/vi/index.js

feature(themes): Introduce new theme variable uiFont

---

package.json
src/themes/kk/index.js

fix(kk theme): update uiFont

---

.travis.yml

ci(travis): install yarn before install

---

package.json
yarn.lock

chore(deps): upgrade babel-eslint from 10.0.1 to 10.0.2

---

src/themes/sol/variables.js

We need the Barlow font on all of sol.no

Barlow on all of SOL

---

package.json
src/molecules/FullscreenAd.js
stories/Ads/fullscreen-ad.js

feature(FullscreenAd): support non-fullscreen ads in fullscreen slots

---

src/molecules/FullscreenAd.js
stories/Ads/fullscreen-ad.js

fix: banner sizing in fullscreen ad

---

src/molecules/FullscreenAd.js

fix(Fullscreen ad): Set adwrapper min height from height prop

---

src/themes/kk/index.js

feat(kk theme): Switch to playfair font on kk

---

src/molecules/FullscreenAd.js

fix(logan): Set fullscreen height to 100vh

---

src/molecules/StickyAd.js

feat(StickyAd): Add top offset prop and pass along rest props

---

stories/Ads/ad-settings-cog.js
stories/Ads/index.js

Planning to replace the helveticons cog with a dorris cog.
TDD, baby!

test(AdSettingsCog): Add story for AdSettingsCog

---

src/atoms/AdSettingsCog.js
src/atoms/AdWrapper.js
src/atoms/SvgIcon/dorris/Svg.js

fix(AdSettingsCog): switch to dorris icon; fix positioning issue

---

package.json
src/atoms/SvgIcon/index.js

fix(SvgIcon): Render icons on the server

---

src/atoms/AdSettingsCog.js

Place ad cog on grey strip above ad

fix(AdSettingsCog): Change ad cog placement

---

src/themes/aller/index.js
src/themes/dagbladet-dark/index.js
src/themes/dagbladet/colors.js
src/themes/default-theme/colors.js
src/themes/dinside/colors.js
src/themes/elbil24-dark/index.js
src/themes/elbil24/colors.js
src/themes/kk/colors.js
src/themes/light-theme/index.js
src/themes/mat/colors.js
src/themes/seher/index.js
src/themes/start/colors.js
src/themes/topp/colors.js
src/themes/vi/colors.js
src/utils/shade-colors.js

fixes https://github.com/dbmedialab/shiny/issues/600

refactor(theme): dedupe shadowing color code

---

src/molecules/FullscreenAd.js
stories/Ads/fullscreen-ad.js

fix: add adunit className to fullscreen
