dbmedialab/shiny

.gitignore
package-lock.json
package.json

Since we're going to import these files as a node module in another project, we need to transpile the code.
Since we're not using npm, we can't use the `prepublish` hook. The reasonable way to do this then, is using the `postinstall` hook.

Add postinstall step.

---

src/themes/oppskrift/index.js

I just realized that if you don't override the grid, it will use the horizontalBase from the default theme. Here's a quick fix for the 'oppskrift' theme.

Make oppskrift grid config use its own horizontalBase

---

src/atoms/HorizontalFlexingList.js
src/atoms/LinkBarItem.js
src/atoms/MatHeader/TopBarSearchField.js
src/index.js
src/molecules/HorizontalLinkBar.js
src/utils/hide-with-flexboxgrid-syntax.js
stories/link-bars/MatStory.js
stories/link-bars/index.js

Extract a util from LinkBarLink to hide your styled-component depending on how wide your screen is.
In the Mat-like link bar story:
- Use the search input field from `atoms/MatHeader/TopBarSearchField`
- Otherwise use existing components: HorizontalLinkBar, LinkBarLink etc
- Demonstrate responsiveness in menu

Iterate on recipe header

---

src/molecules/StickyAd.js

Currently the StickyAd has css `top: 0`. Changing this to use `props.theme.variables.verticalBase` instead so the StickyAds align with the rest of the content.

Refactor StickyAd to use verticalBase

---

src/atoms/DymoHeading.js

This is half of the fix for dbmedialab/wolverine-frontend#216

fix: Remove extra vertical whitespace in DymoHeading

---

src/molecules/WallpaperAd.js

Setting these values will make ad blockers set display:none on the div, which will in turn remove large white boxes for people blocking ads.

Fix missing itemtype and itemscope for WallpaperAd

---

src/atoms/VerticalFlexingList.js

Issue with latest releases of styled-components. Styles with `${Ref} + * &` is not showing up. Swapped `*` with `div` to fix the issue for now so we don't end up being too far behind styled-components master. 
The problem does not seem to exist in SSR/next-less apps: https://codesandbox.io/s/32x1xq2woq

Fix dropdown in header (temporary?)

---

.babelrc
package.json
yarn.lock

This feature adds readable classnames into the html and names styled components react components  better so that it's easier to understand what it is. Fixes #375 
Would this cause a performance regression ? should we only use it when `NODE_ENV` is not production or is it ok to on both? and If we should only have it in production, do we need to create 2 builds?

Inject classNames from component name

---

package.json

Take snapshots to send to Percy at 320, 414, 768, 1280.
414 and 768 are the new widths.
```
320x  ~10%
360x  ~17%
375x  ~25%
414x   ~5%
768x  ~12%
1280x  ~5%
1366x  ~4%
1920x  ~8%
```

ci(percy): Add more widths to Percy

---

.storybook/addons.js
package.json
yarn.lock

Make it possible to watch the stories on several viewports. See https://github.com/dbmedialab/wolverine-frontend/pull/361 for example or https://github.com/storybooks/storybook/tree/master/addons/viewport

Adding viewport to storyboard

---

src/atoms/NumberedListItem.js

fix(NumberedListItem): Move ::before to element instead of child

---

.travis.yml

We indirectly depend on anodynos/upath via webpack. upath specifically states it does not support node > 9.
Stable should be added back in as soon as our dependency graph has updated to address this – hopefully it will not be too long.
See anodynos/upath#14
See anodynos/upath#15

ci: Use 9 instead of stable node

---

package.json
stories/link-bars/ButtonStory.js

Implements storybook addon actions on one of the stories, making it easier to debug issues like #446

fix: Make it easier to track events

---

.babelrc
package.json
src/molecules/FullscreenAd.js
src/molecules/LazyProgressiveImage.js
yarn.lock

This PR is in anticipation of upgrading to Next.js 6 in wolverine-frontend, which uses Babel 7.
Note: Babel stuff is in deps instead of devDeps because we currently build shiny on postinstall in wolverine-frontend. Once Shiny is published to npm we can move deps to devDeps.

Update to Babel 7

---

src/atoms/BylineWithTwoLines.js
src/atoms/ColorBox.js
src/atoms/Heading.js
src/atoms/MainRecipe/Quantity.js
src/atoms/PublishedDate.js
src/atoms/loaders/DotLoader.js
src/molecules/Footers/OppskriftFooter.js

This prepares for moving the type color from directly on the colors object to the skinColors object.

refactor: Use getColor and getVariable in all files using the type color

---

package.json

It has a referance to a css files that forces the clients to have a css loader in their webpack config, but it is only used internally by shiny
- [x ] **fix** _(A bug fix_)

Ignore Code.js

---

src/atoms/Code.js
src/atoms/ShinyThemeProvider.js
src/themes/dagbladet/index.js
src/themes/default-theme/index.js
src/themes/dinside/index.js
src/themes/kk/index.js
src/themes/light-theme/index.js
src/themes/mat/index.js
src/themes/seher/index.js
src/themes/sol/index.js
src/utils/css-reset.js

Remove half-assed reset styles from ShinyThemeProvider, and replace them with full-grown reset styles in each theme.
When reset styles are in the theme, you can also put @import rules before your other styles, so that they will parse properly. Fixes #585

feature: Add full-grown reset styles to most themes

---

src/atoms/DymoHeading.js
src/prop-types/index.js
src/themes/seher/index.js
stories/TrysilPlug/index.js
stories/TrysilPlug/text-color-hover.js

If providing `textColorHover` on `TrysilProp` the heading will change
color on hover.

feature(DymoHeading): Change heading color on plug hover

---

package.json
yarn.lock

Shiny is being used together with next.js, that uses uglifyjs 
version 3 of [striptags notes in its readme](https://www.npmjs.com/package/striptags) that it do not support uglifyjs. 
Do keep support we will downgrad our striptag solution.
When we are using a version of next that has this implemented: https://github.com/zeit/next.js/issues/5021

fix:Downgrade striptag, support uglifyjs

---

src/atoms/LogiclessModal.js

This fixes #692 with ads modal being above everything but the header on e.g. SeHer as shown in the screenshot.
z-index chosen was 6 because the header uses 4 and 5. I don't like this, can we do the header without using z-index two places or more?
Suggestions?

fix: Increase z-index on ads modal to put it above header

---

src/atoms/FontIcon.js

Leverage the font-display CSS feature to ensure icons are not user-visible
with a different font not meant for the same icons as the Helveticon webfont is loading.
Fixes dbmedialab/wolverine-frontend#846

fix(FontIcon): Don't display fallback font for Helveticons

---

src/atoms/DontPushTheAdBoundaries.js

No longer assume that the horizontalBase is 1.4rem.

fix(DontPushTheAdBoundaries): Handle different horizontalBase values

---

src/atoms/AdWrapper.js
src/molecules/WallpaperAd.js

refactor(AdWrapper): Add default itemtype and itemscope on ad wrapper

---

src/atoms/ColorTextBox.js
stories/editorialMarking/colorTextBoxAsCol.js
stories/editorialMarking/index.js

Copy the interface from TrysilPlug to optionally use the component as a Col in a Grid.

feature(ColorTextBox): Use colortextbox as col optionally instead of always

---

src/atoms/ColorTextBox.js

Increases the specificity enough to override Col's own properties.
Fixes #822.

fix(ColorTextBox): Fix vertical alignment when used as Col

---

src/atoms/VerticalFlexingList.js

In emotion 10, style tags will be inserted just in time. That means that
they might be inserted just before this component. Which again means
that this component no longer will be an adjacent sibling to the
dropdown button in LinkBarDropdown in our most common use case.
Therefore, we switch to the general sibling selector.

fix(Dropdown): Account for emotion 10 JIT style tags

---

src/atoms/LinkBarElementBase.js

By request from @morganbro, from now on link bar elements will have the same sizes on narrow and wide screens.

feature(LinkBarElement): Link bar elements will now have the same size

---

src/atoms/AdWrapper.js
src/molecules/FullscreenAd.js
src/molecules/StickyAd.js

Emotion 10 introduced using `forwardRef`, which means instead of passing the old prop of `innerRef` to any styled component you can now pass `ref` as in normal React components. Emotion currently supports both but are spewing deprecation warnings when using `innerRef`.
This change will allow us to use `ref`.
We need to pass along `ref` in the parent ad components in wolverine because of intersection observer render props need a DOM element to track.

fix(ad-wrappers): Use forwardRef to adhere to emotion 10 refs

---

src/molecules/ScrollArrowsLinkBar.js

fix(ScrollArrowsLinkBar): Use ref instead of innerRef as per emotion 10

---

src/molecules/Carousel.js

These labels makes the buttons more intuitive for use with screen
readers. For more information, see
https://dequeuniversity.com/rules/axe/2.2/button-name
An even better solution would have been to internationalize these
strings, so that we could have for example norwegian text on norwegian
sites, and danish text on danish sites.

fix(Carousel): Add missing aria labels

---

src/atoms/SeHerLogo.js

The dates were not readable by safari, causing no moment to be a pride moment if you used Safari :(
Now, pride will commence for safari users as well!

fix(SeHerLogo): make date safari friendly

---

package.json

When updating emotion in wolverine we get issues with shiny components not receiving the theme, this seems to be because of shiny using a different version of emotion than wolverine, to avoid having to update emotion in both shiny and wolverine, we set emotion as peer deps so we only use the version of emotion set in wolverine.
This is a breaking change for any project that currently do not have their own version of the following packages:
- emotion-theming
- @emotion/core
- @emotion/styled

fix: Set emotion as peer deps to avoid duplicate versions

---

src/atoms/VerticalFlexingList.js
stories/link-bar-elements/DropdownStory.js

Make css targeting less specific, to allow for more custom structures
inside LinkBarDropdown elements.
Specifically, this will allow for creting a scrollable parent component
outside around a VerticalLinkBar.

fix(VerticalFlexingList, LinkBarDropdown): Allow for scrollers in dropdowns

---

src/atoms/LinkBarElementBase.js
src/atoms/LinkBarSearchField.jsx
src/atoms/SvgIcon/dorris/ArrowDown.js
src/utils/index.js
src/utils/link-bar-element-sizes.js
stories/link-bar-elements/SearchFieldStory.js

We're trying to get rid of all instances of FontIcon, one usage at a time.
This way, we're hoping to achieve performance improvements by not having to load the Helveticons font.
This change is likely to affect most of the headers in the Aller sites.

fix(LinkBarSearchField): switch to dorris icons

---

src/themes/dagbladet/index.js
src/themes/dinside/index.js
src/themes/elbil24/index.js
src/themes/kk/index.js
src/themes/light-theme/index.js
src/themes/mat/index.js
src/themes/seher/index.js
src/themes/sol/index.js
src/themes/start/index.js

Because we had flash of unstyled fonts for some time before correct font loaded, changed font-display to fallback. This should help a little bit by not displaying fonts at all for 100ms while it's loaded

fix(fonts): changed font-display of theme fonts to fallback
